apiVersion: apps/v1
kind: Deployment
metadata:
  name: myalomatika-numbers-generator-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myalomatika-numbers-generator-service-app
  template:
    metadata:
      labels:
        app: myalomatika-numbers-generator-service-app
    spec:
      containers:
        - name: myalomatika-numbers-generator-service-app
          image: cryfish/myalomatika-numbers-generator-service
          ports:
          - containerPort: 7070
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: myalomatika-numbers-generator-service-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: myalomatika-numbers-generator-service-app
  ports:
    - port: 7070
      targetPort: 7070
      nodePort: 32002
      protocol: TCP